//! Round-trip property: for any horned-owl axiom whose shape our IR can
//! faithfully represent, two successive forward conversions through the
//! same pool/vocabulary pair must produce the same internal [`Axiom`].
//!
//! Concretely:
//!
//! ```text
//!   horned_owl::Component                            (input)
//!         │
//!         │ convert_component
//!         ▼
//!   Axiom₁  ──────┐
//!         │       │ axiom_to_component
//!         │       ▼
//!         │   Component'  (semantically equivalent, possibly different shape)
//!         │       │
//!         │       │ convert_component  (same pool + vocab)
//!         │       ▼
//!         └─→ Axiom₂  ← must equal Axiom₁
//! ```
//!
//! The proptest generator excludes `ObjectHasValue`, `ObjectExactCardinality`,
//! `ObjectOneOf`, and `InverseObjectProperty` — those forms either rewrite to
//! a different shape on the way back (per the docs of [`crate::convert_back`])
//! or are deliberately rejected in Phase 0. Their per-axiom round-trip is
//! covered by unit tests in `src/convert_back.rs`.

use horned_owl::model::{
    Build, ClassExpression, Component, DisjointClasses, EquivalentClasses, Individual,
    ObjectPropertyExpression, RcStr, SubClassOf,
};
use owl_dl_core::convert::convert_component;
use owl_dl_core::convert_back::axiom_to_component;
use owl_dl_core::ontology::InternalOntology;
use proptest::prelude::*;

fn b() -> Build<RcStr> {
    Build::new_rc()
}

// ── A restricted ClassExpression generator ────────────────────────────────
//
// Only constructors that survive the reverse direction unchanged. Cardinality
// is allowed (Min and Max only); Exact is excluded because it expands to
// And(Min,Max). HasValue/OneOf are excluded because Nominal reverses to
// `ObjectOneOf([_])`.

fn arb_class_name() -> impl Strategy<Value = String> {
    "[A-D]".prop_map(String::from)
}

fn arb_role_name() -> impl Strategy<Value = String> {
    "[r-t]".prop_map(String::from)
}

fn arb_ind_name() -> impl Strategy<Value = String> {
    "[a-c]".prop_map(String::from)
}

fn arb_ope() -> impl Strategy<Value = ObjectPropertyExpression<RcStr>> {
    arb_role_name().prop_map(|n| ObjectPropertyExpression::ObjectProperty(b().object_property(n)))
}

fn arb_class_expression() -> impl Strategy<Value = ClassExpression<RcStr>> {
    let leaf = arb_class_name().prop_map(|n| ClassExpression::Class(b().class(n)));
    leaf.prop_recursive(3, 16, 3, |inner| {
        prop_oneof![
            // intersection / union — 2 or more operands to avoid the
            // single-operand collapse on intern
            prop::collection::vec(inner.clone(), 2..4)
                .prop_map(ClassExpression::ObjectIntersectionOf),
            prop::collection::vec(inner.clone(), 2..4).prop_map(ClassExpression::ObjectUnionOf),
            inner
                .clone()
                .prop_map(|c| ClassExpression::ObjectComplementOf(Box::new(c))),
            (arb_ope(), inner.clone()).prop_map(|(ope, c)| ClassExpression::ObjectSomeValuesFrom {
                ope,
                bce: Box::new(c),
            }),
            (arb_ope(), inner.clone()).prop_map(|(ope, c)| ClassExpression::ObjectAllValuesFrom {
                ope,
                bce: Box::new(c),
            }),
            (0u32..3, arb_ope(), inner.clone()).prop_map(|(n, ope, c)| {
                ClassExpression::ObjectMinCardinality {
                    n,
                    ope,
                    bce: Box::new(c),
                }
            }),
            (0u32..3, arb_ope(), inner.clone()).prop_map(|(n, ope, c)| {
                ClassExpression::ObjectMaxCardinality {
                    n,
                    ope,
                    bce: Box::new(c),
                }
            }),
            arb_ope().prop_map(ClassExpression::ObjectHasSelf),
            // Standalone Class leaves are already generated by the base case;
            // include a second copy here so deeper trees keep producing them.
            inner.clone().prop_map(|c| c),
        ]
    })
}

fn arb_named_ind() -> impl Strategy<Value = Individual<RcStr>> {
    arb_ind_name().prop_map(|n| Individual::Named(b().named_individual(n)))
}

fn arb_component() -> impl Strategy<Value = Component<RcStr>> {
    prop_oneof![
        (arb_class_expression(), arb_class_expression())
            .prop_map(|(sub, sup)| Component::SubClassOf(SubClassOf { sub, sup })),
        prop::collection::vec(arb_class_expression(), 2..4)
            .prop_map(|xs| Component::EquivalentClasses(EquivalentClasses(xs))),
        prop::collection::vec(arb_class_expression(), 2..4)
            .prop_map(|xs| Component::DisjointClasses(DisjointClasses(xs))),
        (arb_ope(), arb_class_expression()).prop_map(|(ope, ce)| {
            Component::ObjectPropertyDomain(horned_owl::model::ObjectPropertyDomain { ope, ce })
        }),
        (arb_ope(), arb_class_expression()).prop_map(|(ope, ce)| {
            Component::ObjectPropertyRange(horned_owl::model::ObjectPropertyRange { ope, ce })
        }),
        arb_ope().prop_map(|ope| Component::TransitiveObjectProperty(
            horned_owl::model::TransitiveObjectProperty(ope),
        )),
        arb_ope().prop_map(|ope| Component::FunctionalObjectProperty(
            horned_owl::model::FunctionalObjectProperty(ope),
        )),
        arb_ope().prop_map(|ope| Component::SymmetricObjectProperty(
            horned_owl::model::SymmetricObjectProperty(ope),
        )),
        (arb_class_expression(), arb_named_ind()).prop_map(|(ce, i)| {
            Component::ClassAssertion(horned_owl::model::ClassAssertion { ce, i })
        }),
        (arb_ope(), arb_named_ind(), arb_named_ind()).prop_map(|(ope, from, to)| {
            Component::ObjectPropertyAssertion(horned_owl::model::ObjectPropertyAssertion {
                ope,
                from,
                to,
            })
        }),
    ]
}

proptest! {
    #![proptest_config(ProptestConfig {
        cases: 200,
        ..ProptestConfig::default()
    })]

    /// Forward → reverse → forward must reach the same internal Axiom when
    /// using a single shared pool/vocabulary pair.
    #[test]
    fn forward_reverse_forward_is_idempotent(component in arb_component()) {
        let mut o = InternalOntology::new();
        let ax1 = convert_component(&component, &mut o.vocabulary, &mut o.concepts)
            .map_err(|e| TestCaseError::reject(format!("first convert failed: {e}")))?
            .ok_or_else(|| TestCaseError::reject("first convert returned None"))?;
        let build = b();
        let component_back = axiom_to_component(&ax1, &o, &build);
        let ax2 = convert_component(&component_back, &mut o.vocabulary, &mut o.concepts)
            .map_err(|e| TestCaseError::fail(format!("second convert failed: {e}")))?
            .ok_or_else(|| TestCaseError::fail("second convert returned None"))?;
        prop_assert_eq!(ax1, ax2);
    }
}
