#![allow(clippy::doc_markdown)]
//! A `≥n` over an INVERSE role is never generated by the wedge (`HF3a` is
//! forward-only), so it was silently unenforced (#190 gap 1). The issue argued
//! that could only stall, which holds when the `≥n` is a disjunct. As a plain
//! Horn head it fires once, generates nothing, and the run ends in a trusted
//! `Sat`: `A ⊑ ≥2 q.D ⊓ ≤1 q.D` with `q` declared inverse of `p` came back
//! satisfiable with `incomplete: false`, and its ABox twin `consistent`.
//!
//! The wedge now generates inverse `≥n` successors the way it already builds
//! an `∃R⁻` witness (an `R⁻`-labelled edge to a fresh node). Every verdict
//! below is HermiT's.

use owl_dl_reasoner::{classify, is_consistent};

/// `InverseObjectProperties(:p :q)` makes the canonicaliser rewrite `q` to
/// `p⁻`, which is what routes a `≥n q` onto the inverse path. The `∀p` axiom
/// keeps every fixture out of the EL fast path.
fn ontology(axioms: &str) -> String {
    format!(
        "Prefix(:=<http://ex.org/#>)
Prefix(owl:=<http://www.w3.org/2002/07/owl#>)
Ontology(<http://ex.org/ial>
Declaration(Class(:A)) Declaration(Class(:B)) Declaration(Class(:C)) Declaration(Class(:D))
Declaration(Class(:E)) Declaration(Class(:W))
Declaration(ObjectProperty(:p)) Declaration(ObjectProperty(:q))
Declaration(NamedIndividual(:a))
InverseObjectProperties(:p :q)
SubClassOf(:B ObjectAllValuesFrom(:p :E))
{axioms}
)
"
    )
}

fn parse(axioms: &str) -> horned_owl::ontology::set::SetOntology<horned_owl::model::RcStr> {
    let mut cur = std::io::Cursor::new(ontology(axioms));
    let (onto, _) =
        horned_owl::io::ofn::reader::read(&mut cur, horned_owl::io::ParserConfiguration::default())
            .expect("parse");
    onto
}

fn classified(axioms: &str) -> owl_dl_reasoner::Classification {
    classify(&parse(axioms)).expect("classify")
}

fn unsat(axioms: &str) -> Vec<String> {
    classified(axioms)
        .unsatisfiable_classes()
        .into_iter()
        .map(str::to_owned)
        .collect()
}

const MIN2_MAX1: &str = "SubClassOf(:A ObjectMinCardinality(2 :q :D)) \
                         SubClassOf(:A ObjectMaxCardinality(1 :q :D))";

#[test]
fn inverse_min_above_max_is_unsatisfiable() {
    assert_eq!(unsat(MIN2_MAX1), ["http://ex.org/#A"]);
}

#[test]
fn inverse_min_above_unqualified_max_is_unsatisfiable() {
    let ax = "SubClassOf(:A ObjectMinCardinality(3 :q :D)) \
              SubClassOf(:A ObjectMaxCardinality(2 :q owl:Thing))";
    assert_eq!(unsat(ax), ["http://ex.org/#A"]);
}

#[test]
fn inverse_min_above_max_makes_an_instance_inconsistent() {
    let ax = format!("{MIN2_MAX1} ClassAssertion(:A :a)");
    assert!(!is_consistent(&parse(&ax)).expect("consistent"));
}

/// The bug reproduces only through the inverse declaration: this is the same
/// shape on a plain role, which was always right.
#[test]
fn forward_control_min_above_max_is_unsatisfiable() {
    let ax = "SubClassOf(:A ObjectMinCardinality(2 :p :D)) \
              SubClassOf(:A ObjectMaxCardinality(1 :p :D))";
    assert_eq!(unsat(ax), ["http://ex.org/#A"]);
}

// FP guards: the give-up must not manufacture a clash.

#[test]
fn inverse_min_alone_is_satisfiable() {
    assert!(unsat("SubClassOf(:A ObjectMinCardinality(2 :q :D))").is_empty());
}

#[test]
fn inverse_min_equal_to_max_is_satisfiable() {
    let ax = "SubClassOf(:A ObjectMinCardinality(2 :q :D)) \
              SubClassOf(:A ObjectMaxCardinality(2 :q :D))";
    assert!(unsat(ax).is_empty());
}

#[test]
fn inverse_min_alone_keeps_an_instance_consistent() {
    let ax = "SubClassOf(:A ObjectMinCardinality(2 :q :D)) ClassAssertion(:A :a)";
    assert!(is_consistent(&parse(ax)).expect("consistent"));
}

/// `a` already has two `q`-successors (its asserted, distinct
/// `p`-predecessors), so `≤2 q` forces any generated successor to merge
/// into `b` or `c`. Consistent; the `≥3` twin is not.
const TWO_PREDS: &str = "Declaration(NamedIndividual(:b)) Declaration(NamedIndividual(:c)) \
                         ClassAssertion(:A :a) ObjectPropertyAssertion(:p :b :a) \
                         ObjectPropertyAssertion(:p :c :a) DifferentIndividuals(:b :c)";

#[test]
fn inverse_min_met_by_asserted_predecessors_is_consistent() {
    let ax = format!(
        "SubClassOf(:A ObjectIntersectionOf(ObjectMinCardinality(2 :q owl:Thing) \
         ObjectMaxCardinality(2 :q owl:Thing))) {TWO_PREDS}"
    );
    assert!(is_consistent(&parse(&ax)).expect("consistent"));
}

#[test]
fn inverse_min_above_asserted_predecessors_and_max_is_inconsistent() {
    let ax = format!(
        "SubClassOf(:A ObjectIntersectionOf(ObjectMinCardinality(3 :q owl:Thing) \
         ObjectMaxCardinality(2 :q owl:Thing))) {TWO_PREDS}"
    );
    assert!(!is_consistent(&parse(&ax)).expect("consistent"));
}

/// A generated `q`-successor `y` is a `p`-PREDECESSOR of `A`: `∀q.E` on `y`
/// speaks about `y`'s own `q`-successors, not about `A`.
#[test]
fn forall_on_a_generated_node_does_not_reach_back_with_the_wrong_polarity() {
    let ax = "SubClassOf(:A ObjectMinCardinality(2 :q :D)) \
              SubClassOf(:D ObjectAllValuesFrom(:q :E)) SubClassOf(:A ObjectComplementOf(:E))";
    assert!(unsat(ax).is_empty());
}

/// `A`'s `p`-successor `B` needs two `q`-successors and allows only two, so
/// `A` (already one of them) is merged with a generated `C` node. Disjoint
/// `A`/`C` makes that a clash; without it `A` is satisfiable.
#[test]
fn a_generated_node_merging_with_the_predecessor_carries_its_labels() {
    let shape = "SubClassOf(:A ObjectSomeValuesFrom(:p :B)) \
                 SubClassOf(:B ObjectIntersectionOf(ObjectMinCardinality(2 :q :C) \
                 ObjectMaxCardinality(2 :q owl:Thing)))";
    assert!(unsat(shape).is_empty());
    assert!(unsat(&format!("{shape} DisjointClasses(:A :C)")).contains(&"http://ex.org/#A".into()));
}

/// With `r ⊑ p`, a generated `p⁻` edge is not an `r⁻` edge.
#[test]
fn a_generated_super_role_edge_does_not_count_for_the_sub_role() {
    let ax = "Declaration(ObjectProperty(:r)) SubObjectPropertyOf(:r :p) \
              SubClassOf(:A ObjectIntersectionOf(ObjectMinCardinality(2 :q :D) \
              ObjectMaxCardinality(1 ObjectInverseOf(:r) owl:Thing)))";
    assert!(unsat(ax).is_empty());
}

/// KNOWN GAP, not this fix: `InverseFunctional(p)` with the generator spelled
/// `≥2 q` through the declared inverse. HermiT and Konclude both call `A`
/// unsatisfiable; `classify` says satisfiable with `incomplete: false`. The
/// derived `≤1 p⁻` is never emitted because `inv_func_merge_consumable`
/// (owl-dl-core convert.rs) compares raw role ids before canonicalisation, so
/// it does not see `≥2 q` as `≥2 p⁻`. Spelled `ObjectInverseOf(:p)` it is
/// caught (`inverse_functional_tbox_admission.rs`). FLIP this when the gate
/// learns the declared-inverse spelling.
#[test]
fn inverse_functional_with_a_declared_inverse_min_is_still_missed() {
    let ax = "SubClassOf(:A ObjectMinCardinality(2 :q :D)) InverseFunctionalObjectProperty(:p)";
    assert!(
        unsat(ax).is_empty(),
        "the declared-inverse IF gap closed: flip this test to assert A unsat"
    );
}

/// `≥2 q.D` ⊑ `≥2 q.⊤` holds (HermiT). FLIPPED from
/// `…_is_flagged_incomplete`: a give-up-only fix left this a flagged MISS,
/// because classify's per-pair path counts a wedge `Stalled` as a timeout.
/// Generating the inverse successors is what proves it.
#[test]
fn inverse_min_subsumption_is_derived() {
    let ax = "SubClassOf(:A ObjectMinCardinality(2 :q :D)) \
              EquivalentClasses(:C ObjectMinCardinality(2 :q owl:Thing))";
    assert!(classified(ax).is_subclass("http://ex.org/#A", "http://ex.org/#C"));
}
